#! /bin/sh
bspc config border_width         3
bspc config -m eDP1 window_gap	 $BSPWM_PAD
bspc config -m HDMI1 window_gap 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor eDP1 -d q w e r t y
bspc monitor HDMI1 -d u i

bspc config focused_border_color "#e0e0e0"
bspc config active_border_color "#BDC3C7"
bspc config normal_border_color "#7F8C8D"
bspc config presel_feedback_color "#2ECC71"

panel_loader &
